export const SAMPLE_PROJECT = {
  projectName: 'Sample_Certificate_Project',
  bgType: 'classic',
  customBg: null,
  bgTransform: { width: 100, height: 100, x: 0, y: 0 },
  logoImg: null,
  canvasSize: { width: 1100, height: 850, label: 'US Letter Landscape' },
  globalData: {
    orgName: 'BatchCert Academy',
    orgSubtext: 'Office of Student Affairs',
    dateLine: 'Given this 11th day of August, 2026',
    certificateTitle: 'Certificate of Appreciation',
    eventDuties: '',
    bodyTemplate: 'In grateful recognition of outstanding service and dedication as {{Position}} within the {{Department}} program.',
  },
  csvHeaders: ['Name', 'Position', 'Department'],
  awardees: [
    {
      id: 'sample_1',
      name: 'Jane Doe',
      position: 'Student Leader',
      csvData: { Name: 'Jane Doe', Position: 'Student Leader', Department: 'Student Council' },
      hasCustomLayout: false,
      customElements: null,
      customSignatories: null,
    },
    {
      id: 'sample_2',
      name: 'John Smith',
      position: 'Volunteer Coordinator',
      csvData: { Name: 'John Smith', Position: 'Volunteer Coordinator', Department: 'Community Outreach' },
      hasCustomLayout: false,
      customElements: null,
      customSignatories: null,
    },
    {
      id: 'sample_3',
      name: 'Maria Garcia',
      position: 'Event Organizer',
      csvData: { Name: 'Maria Garcia', Position: 'Event Organizer', Department: 'Arts & Culture' },
      hasCustomLayout: false,
      customElements: null,
      customSignatories: null,
    },
  ],
  signatories: [
    { id: 'sig_1', name: 'Dr. Elena Reyes', title: 'Director', signatureImg: null },
    { id: 'sig_2', name: 'Prof. James Chen', title: 'Dean', signatureImg: null },
  ],
  elements: [
    {
      id: 'sample_orgName',
      type: 'text',
      key: 'orgName',
      label: 'Organization Name',
      text: 'BatchCert Academy',
      x: 50,
      y: 11,
      font: 'Cinzel',
      fontSize: 24,
      color: '#581c87',
      bold: true,
      italic: false,
      underline: false,
      align: 'center',
      maxWidth: 85,
      visible: true,
    },
    {
      id: 'sample_orgSubtext',
      type: 'text',
      key: 'orgSubtext',
      label: 'Organization Subtext',
      text: 'Office of Student Affairs',
      x: 50,
      y: 16,
      font: 'Inter',
      fontSize: 18,
      color: '#6b7280',
      bold: false,
      italic: false,
      underline: false,
      align: 'center',
      maxWidth: 80,
      visible: true,
    },
    {
      id: 'sample_certificateTitle',
      type: 'text',
      key: 'certificateTitle',
      label: 'Certificate Title',
      text: 'Certificate of Appreciation',
      x: 50,
      y: 25,
      font: 'Playfair Display',
      fontSize: 32,
      color: '#581c87',
      bold: true,
      italic: false,
      underline: false,
      align: 'center',
      maxWidth: 85,
      visible: true,
    },
    {
      id: 'sample_awardeeName',
      type: 'text',
      key: 'awardeeName',
      label: 'Awardee Name',
      text: '',
      x: 50,
      y: 36,
      font: 'Great Vibes',
      fontSize: 36,
      color: '#581c87',
      bold: true,
      italic: false,
      underline: false,
      align: 'center',
      maxWidth: 90,
      visible: true,
    },
    {
      id: 'sample_awardeePosition',
      type: 'text',
      key: 'awardeePosition',
      label: 'Awardee Position',
      text: '',
      x: 50,
      y: 44,
      font: 'Montserrat',
      fontSize: 18,
      color: '#1f2937',
      bold: true,
      italic: false,
      underline: false,
      align: 'center',
      maxWidth: 85,
      visible: true,
    },
    {
      id: 'sample_bodyTemplate',
      type: 'text',
      key: 'bodyTemplate',
      label: 'Body Template',
      text: 'In grateful recognition of outstanding service and dedication as {{Position}} within the {{Department}} program.',
      x: 50,
      y: 55,
      font: 'Cormorant Garamond',
      fontSize: 18,
      color: '#374151',
      bold: false,
      italic: false,
      underline: false,
      align: 'center',
      maxWidth: 78,
      visible: true,
    },
    {
      id: 'sample_dateLine',
      type: 'text',
      key: 'dateLine',
      label: 'Date Line',
      text: 'Given this 11th day of August, 2026',
      x: 50,
      y: 74,
      font: 'Inter',
      fontSize: 16,
      color: '#6b7280',
      bold: false,
      italic: false,
      underline: false,
      align: 'center',
      maxWidth: 80,
      visible: true,
    },
    {
      id: 'sample_sig1_name',
      type: 'text',
      sigId: 'sig_1',
      sigField: 'name',
      label: 'Signatory 1 Name',
      text: 'Dr. Elena Reyes',
      x: 30,
      y: 87,
      font: 'Inter',
      fontSize: 18,
      color: '#1f2937',
      bold: true,
      italic: false,
      underline: false,
      align: 'center',
      maxWidth: 40,
      visible: true,
    },
    {
      id: 'sample_sig1_title',
      type: 'text',
      sigId: 'sig_1',
      sigField: 'title',
      label: 'Signatory 1 Title',
      text: 'Director',
      x: 30,
      y: 91,
      font: 'Inter',
      fontSize: 14,
      color: '#4b5563',
      bold: false,
      italic: false,
      underline: false,
      align: 'center',
      maxWidth: 40,
      visible: true,
    },
    {
      id: 'sample_sig2_name',
      type: 'text',
      sigId: 'sig_2',
      sigField: 'name',
      label: 'Signatory 2 Name',
      text: 'Prof. James Chen',
      x: 70,
      y: 87,
      font: 'Inter',
      fontSize: 18,
      color: '#1f2937',
      bold: true,
      italic: false,
      underline: false,
      align: 'center',
      maxWidth: 40,
      visible: true,
    },
    {
      id: 'sample_sig2_title',
      type: 'text',
      sigId: 'sig_2',
      sigField: 'title',
      label: 'Signatory 2 Title',
      text: 'Dean',
      x: 70,
      y: 91,
      font: 'Inter',
      fontSize: 14,
      color: '#4b5563',
      bold: false,
      italic: false,
      underline: false,
      align: 'center',
      maxWidth: 40,
      visible: true,
    },
  ],
};
